Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.

  SubnetId:
      Type: AWS::EC2::Subnet::Id
      Description: SubnetId of an existing subnet (for the primary network) in your
        Virtual Private Cloud (VPC)
      ConstraintDescription: must be an existing subnet in the selected Virtual Private
        Cloud.
  # PrimaryIPAddress:
  #   Type: String
  #   Description: Primary private IP. This must be a valid IP address for Subnet
  #   AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
  #   ConstraintDescription: must be a valid IP address of the form x.x.x.x.

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: webserver-group2
      GroupDescription: Security Group for EC2
      VpcId: !Ref 'VpcId'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: GoWebserver

# Network Interface
  # Eth0:
  #   Type: AWS::EC2::NetworkInterface
  #   Properties:
  #     Description: eth0
  #     GroupSet: [!Ref 'MySecurityGroup']
  #     PrivateIpAddress:  '172.31.64.20'
  #     SourceDestCheck: 'true'
  #     SubnetId: !Ref 'SubnetId'
  
  # # EIP
  # EIP1:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc

  # # EIPAssociation
  # EIPAssoc1:
  #   Type: AWS::EC2::EIPAssociation
  #   Properties:
  #     NetworkInterfaceId: !Ref 'Eth0'
  #     AllocationId: !GetAtt [EIP1, AllocationId]

# EC2 Instance
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 'ami-0ff8a91507f77f867'
      InstanceType: t2.micro
      KeyName: chairs
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: '0'
          SubnetId: !Ref 'SubnetId'
          GroupSet: [!Ref 'MySecurityGroup']
      BlockDeviceMappings:
        - DeviceName: /dev/sdc
          VirtualName: ephemeral0
              
        
          